spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.sql.init.mode=never
spring.h2.console.enabled=false
spring.security.oauth2.resourceserver.jwt.issuer-uri=${OIDC_ISSUER_URI}
management.endpoints.web.exposure.include=health,info
